### ISSUE TITLE
Unable to integrate "client" in an existing Android Studio project

### ISSUE THREAD

**Issue by cjeanneret** [i2p/i2p.android.base#1]
Hello @str4d,

Trying to get it working in orwall — I'm a bit lost, even with your tweeter support :(. Thus, I'd rather create an issue in order to get the whole thing in place.

So.
What I think is the normal way to integrate external lib with gradle in AS:
- edit settings.gradle, add new lib on the "include" line:

```
include ':app', ':external:super-commands:libraries:RootCommands',':external:NetCipher:libnetcipher', ':external:i2p:client'
```
- edit app/build.gradle in order to make it compile the new lib in the project:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    // You must install or update the Support Repository through the SDK manager to use this dependency.
    //compile 'com.android.support:support-v4:19.+'
    compile project(':external:super-commands:libraries:RootCommands')
    compile project(':external:NetCipher:libnetcipher')
    compile project(':external:i2p:client')
}
```

This works for netCipher and super-commands libs, but not for i2p client. Here's the error message:

```
Error:(20, 0) Project with path ':routerjars' could not be found in project ':external:i2p:client'.
```

I also tried to include external/i2p directly:

```
Error:Configuration with name 'default' not found.
```

I think the main problem is in the build.gradle embedded in client directory: it depends on some external directory/configuration, and gradle doesn't seem to understand what to do with this "routerjars" thing.

Thanks in advance for your lights/advices.

Cheers,

C.

**Comment by str4d** [comment]
That method is not going to work for the I2P client library, because of the way that the upstream I2P jars are integrated.

The way to use the I2P client library is with a dependency line like:
`compile 'net.i2p.android:client:0.5.1@aar'`

You can get the AAR library either by having Gradle fetch it automatically from JCenter or Maven Central, or by building the client library yourself and installing it in your local Maven repo (`~/.m2`) with `gradle client:installArchives`.
